export const envVar = {
  ENVIRONMENT: process.env.ENVIRONMENT,
  BACKEND_API_URL: process.env.BACKEND_API_URL,

  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET,
  JWT_ACCESS_TOKEN_EXPIRE_IN: process.env.JWT_ACCESS_TOKEN_EXPIRE_IN,
  JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_EXPIRE_IN: process.env.JWT_REFRESH_TOKEN_EXPIRE_IN,
};
